name 'example42-multipath'
version '2.0.11'

author 'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source 'https://github.com/example42/puppet-multipath'
summary 'Puppet module for multipath'
description 'This module installs and manages multipath. Check README for details.'
dependency 'example42/puppi', '>=2.0.0'
